/* tslint:disable */
/* eslint-disable */
/**
 * Photon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AddressPlace {
    'alpha'?: string;
    'components'?: { [key: string]: string; };
    'country'?: string;
    'description': string;
    'formatted_address'?: string;
    'latitude'?: number;
    'longitude'?: number;
    'place_id': string;
}
export interface AddressPlaceAutocomplete {
    'description': string;
    'place_id': string;
    'structured_formatting'?: StructuredFormat;
}
export interface ErrorDetail {
    /**
     * Where the error occurred, e.g. \'body.items[3].tags\' or \'path.thing-id\'
     */
    'location'?: string;
    /**
     * Error message text
     */
    'message'?: string;
    /**
     * The value at the given location
     */
    'value'?: any;
}
export interface ErrorModel {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    'detail'?: string;
    /**
     * Optional list of individual error details
     */
    'errors'?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    'instance'?: string;
    /**
     * HTTP status code
     */
    'status'?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    'title'?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    'type'?: string;
}
export interface HomeGetOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'message': string;
}
export interface PasswordForgotPostInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'email': string;
}
export interface PasswordForgotPostOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'message': string;
}
export interface PasswordResetPostInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'code': string;
    'password': string;
}
export interface PasswordResetPostOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'message': string;
}
export interface PlaceGetOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'object': AddressPlace;
}
export interface PlacesGetOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'list': Array<AddressPlaceAutocomplete> | null;
}
export interface Profile {
    'created': string;
    'email': string;
    'id': number;
    'image': string;
    'name': string;
}
export interface ProfileDeleteOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'object': Profile;
}
export interface ProfileGetOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'object': Profile;
}
export interface ProfileImageUpdateOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'object': Profile;
}
export interface ProfileUpdateEmailInputBody {
    [key: string]: any;

    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'email': string;
    'id': number;
}
export interface ProfileUpdateEmailOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'object': Profile;
}
export interface ProfileUpdateInputBody {
    [key: string]: any;

    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'id': number;
    'name': string;
}
export interface ProfileUpdateOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'object': Profile;
}
export interface SignInInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'email': string;
    'password': string;
}
export interface SignInOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'token': string;
}
export interface SignInSupabaseInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'token': string;
}
export interface SignInSupabaseOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'token': string;
}
export interface SignUpInputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'email': string;
    'password': string;
}
export interface SignUpOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     */
    '$schema'?: string;
    'token': string;
}
export interface StructuredFormat {
    'main_text': string;
    'secondary_text': string;
}

/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {PasswordForgotPostInputBody} passwordForgotPostInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        passwordForgotPostAPI: async (passwordForgotPostInputBody: PasswordForgotPostInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'passwordForgotPostInputBody' is not null or undefined
            assertParamExists('passwordForgotPostAPI', 'passwordForgotPostInputBody', passwordForgotPostInputBody)
            const localVarPath = `/auth/passwordforgot`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(passwordForgotPostInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PasswordResetPostInputBody} passwordResetPostInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        passwordResetPostAPI: async (passwordResetPostInputBody: PasswordResetPostInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'passwordResetPostInputBody' is not null or undefined
            assertParamExists('passwordResetPostAPI', 'passwordResetPostInputBody', passwordResetPostInputBody)
            const localVarPath = `/auth/passwordreset`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(passwordResetPostInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SignInInputBody} signInInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signInAPI: async (signInInputBody: SignInInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signInInputBody' is not null or undefined
            assertParamExists('signInAPI', 'signInInputBody', signInInputBody)
            const localVarPath = `/auth/signin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signInInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SignInSupabaseInputBody} signInSupabaseInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signInSupabaseAPI: async (signInSupabaseInputBody: SignInSupabaseInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signInSupabaseInputBody' is not null or undefined
            assertParamExists('signInSupabaseAPI', 'signInSupabaseInputBody', signInSupabaseInputBody)
            const localVarPath = `/auth/signin/supabase`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signInSupabaseInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SignUpInputBody} signUpInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpAPI: async (signUpInputBody: SignUpInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signUpInputBody' is not null or undefined
            assertParamExists('signUpAPI', 'signUpInputBody', signUpInputBody)
            const localVarPath = `/auth/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signUpInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {PasswordForgotPostInputBody} passwordForgotPostInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async passwordForgotPostAPI(passwordForgotPostInputBody: PasswordForgotPostInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PasswordForgotPostOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.passwordForgotPostAPI(passwordForgotPostInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.passwordForgotPostAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PasswordResetPostInputBody} passwordResetPostInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async passwordResetPostAPI(passwordResetPostInputBody: PasswordResetPostInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PasswordResetPostOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.passwordResetPostAPI(passwordResetPostInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.passwordResetPostAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SignInInputBody} signInInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signInAPI(signInInputBody: SignInInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignInOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signInAPI(signInInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signInAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SignInSupabaseInputBody} signInSupabaseInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signInSupabaseAPI(signInSupabaseInputBody: SignInSupabaseInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignInSupabaseOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signInSupabaseAPI(signInSupabaseInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signInSupabaseAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SignUpInputBody} signUpInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signUpAPI(signUpInputBody: SignUpInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignUpOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signUpAPI(signUpInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signUpAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @param {PasswordForgotPostInputBody} passwordForgotPostInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        passwordForgotPostAPI(passwordForgotPostInputBody: PasswordForgotPostInputBody, options?: RawAxiosRequestConfig): AxiosPromise<PasswordForgotPostOutputBody> {
            return localVarFp.passwordForgotPostAPI(passwordForgotPostInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PasswordResetPostInputBody} passwordResetPostInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        passwordResetPostAPI(passwordResetPostInputBody: PasswordResetPostInputBody, options?: RawAxiosRequestConfig): AxiosPromise<PasswordResetPostOutputBody> {
            return localVarFp.passwordResetPostAPI(passwordResetPostInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SignInInputBody} signInInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signInAPI(signInInputBody: SignInInputBody, options?: RawAxiosRequestConfig): AxiosPromise<SignInOutputBody> {
            return localVarFp.signInAPI(signInInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SignInSupabaseInputBody} signInSupabaseInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signInSupabaseAPI(signInSupabaseInputBody: SignInSupabaseInputBody, options?: RawAxiosRequestConfig): AxiosPromise<SignInSupabaseOutputBody> {
            return localVarFp.signInSupabaseAPI(signInSupabaseInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SignUpInputBody} signUpInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpAPI(signUpInputBody: SignUpInputBody, options?: RawAxiosRequestConfig): AxiosPromise<SignUpOutputBody> {
            return localVarFp.signUpAPI(signUpInputBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @param {PasswordForgotPostInputBody} passwordForgotPostInputBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public passwordForgotPostAPI(passwordForgotPostInputBody: PasswordForgotPostInputBody, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).passwordForgotPostAPI(passwordForgotPostInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {PasswordResetPostInputBody} passwordResetPostInputBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public passwordResetPostAPI(passwordResetPostInputBody: PasswordResetPostInputBody, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).passwordResetPostAPI(passwordResetPostInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SignInInputBody} signInInputBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public signInAPI(signInInputBody: SignInInputBody, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signInAPI(signInInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SignInSupabaseInputBody} signInSupabaseInputBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public signInSupabaseAPI(signInSupabaseInputBody: SignInSupabaseInputBody, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signInSupabaseAPI(signInSupabaseInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SignUpInputBody} signUpInputBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public signUpAPI(signUpInputBody: SignUpInputBody, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signUpAPI(signUpInputBody, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HomeApi - axios parameter creator
 */
export const HomeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeGetAPI: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeApi - functional programming interface
 */
export const HomeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HomeApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async homeGetAPI(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HomeGetOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.homeGetAPI(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeApi.homeGetAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HomeApi - factory interface
 */
export const HomeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HomeApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeGetAPI(options?: RawAxiosRequestConfig): AxiosPromise<HomeGetOutputBody> {
            return localVarFp.homeGetAPI(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HomeApi - object-oriented interface
 */
export class HomeApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public homeGetAPI(options?: RawAxiosRequestConfig) {
        return HomeApiFp(this.configuration).homeGetAPI(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PlacesApi - axios parameter creator
 */
export const PlacesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} placeId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        placeGetAPI: async (placeId: string, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'placeId' is not null or undefined
            assertParamExists('placeGetAPI', 'placeId', placeId)
            const localVarPath = `/places/{place_id}`
                .replace('{place_id}', encodeURIComponent(String(placeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [authorization] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        placesGetAPI: async (authorization?: string, search?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/places`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PlacesApi - functional programming interface
 */
export const PlacesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PlacesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} placeId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async placeGetAPI(placeId: string, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlaceGetOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.placeGetAPI(placeId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlacesApi.placeGetAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [authorization] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async placesGetAPI(authorization?: string, search?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PlacesGetOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.placesGetAPI(authorization, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PlacesApi.placesGetAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PlacesApi - factory interface
 */
export const PlacesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PlacesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} placeId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        placeGetAPI(placeId: string, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<PlaceGetOutputBody> {
            return localVarFp.placeGetAPI(placeId, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [authorization] 
         * @param {string} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        placesGetAPI(authorization?: string, search?: string, options?: RawAxiosRequestConfig): AxiosPromise<PlacesGetOutputBody> {
            return localVarFp.placesGetAPI(authorization, search, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PlacesApi - object-oriented interface
 */
export class PlacesApi extends BaseAPI {
    /**
     * 
     * @param {string} placeId 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public placeGetAPI(placeId: string, authorization?: string, options?: RawAxiosRequestConfig) {
        return PlacesApiFp(this.configuration).placeGetAPI(placeId, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [authorization] 
     * @param {string} [search] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public placesGetAPI(authorization?: string, search?: string, options?: RawAxiosRequestConfig) {
        return PlacesApiFp(this.configuration).placesGetAPI(authorization, search, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileDeleteAPI: async (authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileGetAPI: async (authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {File} file 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileImageUpdateAPI: async (file: File, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('profileImageUpdateAPI', 'file', file)
            const localVarPath = `/users/profile/image`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ProfileUpdateInputBody} profileUpdateInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileUpdateAPI: async (profileUpdateInputBody: ProfileUpdateInputBody, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'profileUpdateInputBody' is not null or undefined
            assertParamExists('profileUpdateAPI', 'profileUpdateInputBody', profileUpdateInputBody)
            const localVarPath = `/users/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(profileUpdateInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ProfileUpdateEmailInputBody} profileUpdateEmailInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileUpdateEmailAPI: async (profileUpdateEmailInputBody: ProfileUpdateEmailInputBody, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'profileUpdateEmailInputBody' is not null or undefined
            assertParamExists('profileUpdateEmailAPI', 'profileUpdateEmailInputBody', profileUpdateEmailInputBody)
            const localVarPath = `/users/profile/email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(profileUpdateEmailInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileDeleteAPI(authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileDeleteOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profileDeleteAPI(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.profileDeleteAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileGetAPI(authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileGetOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profileGetAPI(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.profileGetAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {File} file 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileImageUpdateAPI(file: File, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileImageUpdateOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profileImageUpdateAPI(file, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.profileImageUpdateAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ProfileUpdateInputBody} profileUpdateInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileUpdateAPI(profileUpdateInputBody: ProfileUpdateInputBody, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileUpdateOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profileUpdateAPI(profileUpdateInputBody, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.profileUpdateAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ProfileUpdateEmailInputBody} profileUpdateEmailInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileUpdateEmailAPI(profileUpdateEmailInputBody: ProfileUpdateEmailInputBody, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileUpdateEmailOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profileUpdateEmailAPI(profileUpdateEmailInputBody, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.profileUpdateEmailAPI']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileDeleteAPI(authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<ProfileDeleteOutputBody> {
            return localVarFp.profileDeleteAPI(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileGetAPI(authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<ProfileGetOutputBody> {
            return localVarFp.profileGetAPI(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {File} file 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileImageUpdateAPI(file: File, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<ProfileImageUpdateOutputBody> {
            return localVarFp.profileImageUpdateAPI(file, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileUpdateInputBody} profileUpdateInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileUpdateAPI(profileUpdateInputBody: ProfileUpdateInputBody, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<ProfileUpdateOutputBody> {
            return localVarFp.profileUpdateAPI(profileUpdateInputBody, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileUpdateEmailInputBody} profileUpdateEmailInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileUpdateEmailAPI(profileUpdateEmailInputBody: ProfileUpdateEmailInputBody, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<ProfileUpdateEmailOutputBody> {
            return localVarFp.profileUpdateEmailAPI(profileUpdateEmailInputBody, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public profileDeleteAPI(authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).profileDeleteAPI(authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public profileGetAPI(authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).profileGetAPI(authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {File} file 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public profileImageUpdateAPI(file: File, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).profileImageUpdateAPI(file, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileUpdateInputBody} profileUpdateInputBody 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public profileUpdateAPI(profileUpdateInputBody: ProfileUpdateInputBody, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).profileUpdateAPI(profileUpdateInputBody, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileUpdateEmailInputBody} profileUpdateEmailInputBody 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public profileUpdateEmailAPI(profileUpdateEmailInputBody: ProfileUpdateEmailInputBody, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).profileUpdateEmailAPI(profileUpdateEmailInputBody, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}



